services:
  aerostack2:
    image: aerostack2_roscon25
    build:
      context: ./docker/
      dockerfile: Dockerfile
    container_name: aerostack2_roscon25
    environment:
      DISPLAY: $DISPLAY
      ROS_LOCALHOST_ONLY: 1
    privileged: true
    volumes:
      # X11
      - ~/.Xauthority:/root/.Xauthority
      # 
      - /dev/:/dev
      - .:/root/demo_ROSConES25/
    network_mode: "host"
    command: tail -f /dev/null
